FROM python:3.8

ENV PYTHONDONTBITEWRITECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /site/

RUN pip install --upgrade pip
RUN pip install django

COPY . /site/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]